services:

    Goat\Domain\Repository\Bridge\Symfony\DependencyInjection\ContainerRepositoryRegistry:
        arguments: [] # Will be populated by a compiler pass.

    goat.domain.repository.registry:
        alias: Goat\Domain\Repository\Bridge\Symfony\DependencyInjection\ContainerRepositoryRegistry

    Goat\Domain\Repository\Registry\RepositoryRegistry:
        alias: goat.domain.repository.registry

    Goat\Domain\Repository\Hydration\RepositoryHydrator:
        arguments: ['@goat.hydrator_registy']

    goat.domain.repository.hydrator:
        alias: Goat\Domain\Repository\Hydration\RepositoryHydrator
